# This file is used to define the objects available on your site.

[tutorial]
template = "tutorial"
title = "string"
content = "markdown"
nav_title = "string"

[scalar]
name = "string"
description = "markdown"

[manifesto]
title = "string"
body = "markdown"
