# This file is used to define the objects available on your site.

[home]
header = "image"
header_alt = "string"
videos_title = "string"
personas_title = "string"
pricing_title = "string"
pricing_content = "markdown"

[home.sections]
title = "string"
content = "markdown"
top_right_image = "image"
bottom_left_image = "image"
invert_images = "boolean"

[home.videos]
title = "string"
video = "video"

[home.personas]
image = "image"
title = "string"
content = "markdown"

[manifesto]
title = "string"
content = "markdown"

[docs]
title = "string"
description = "markdown"
template = "docs"
[docs.sections]
title = "string"
content = "markdown"

[cli_docs]
command = "string"
content = "markdown"
template = "cli_docs"
[cli_docs.options]
flags = "string"
description = "string"
[cli_docs.arguments]
arg = "string"
description = "string"
