# This file is used to define the objects available on your site.

[home]
title = "string"
description = "string"
header = "image"
header_alt = "string"
manifesto_link_title = "string"
videos_title = "string"
personas_title = "string"
contact_title = "string"
pricing_title = "string"
pricing_content = "markdown"
discord_url = "string"

[home.sections]
title = "string"
content = "markdown"

[home.videos]
title = "string"
video = "video"
poster = "string"

[manifesto]
title = "string"
content = "markdown"

[docs]
title = "string"
description = "markdown"
template = "docs"
[docs.sections]
title = "string"
content = "markdown"

[cli]
command = "string"
content = "markdown"
template = "cli"
[cli.options]
flags = "string"
description = "string"
[cli.arguments]
arg = "string"
description = "string"
