# This file is used to define the objects available on your site.

[page]
content = "markdown"

[recipe]
content = "markdown"
description = "string"
image = "string"
name = "string"
template = "recipe"

[project]
content = "markdown"
image = "string"
name = "string"
template = "project"
