# This file is used to define the objects available on your site.

[tutorial]
template = "tutorial"
name = "string"
content = "markdown"

[scalar]
name = "string"
description = "markdown"

[manifesto]
title = "string"
body = "markdown"