order = -1
title = "Archival | Content-First Websites"
description = """
Archival is the simplest way to build an easy-to-maintain website for your business, product, or brand.
"""
header_alt = "archival.dev"
personas_title = "What Can Archival do for Me?"
manifesto_link_title = "Read the archival manifesto"
videos_title = "Show Me How It Works"
contact_title = "Connect With Us"
pricing_title = "Pricing"
pricing_content = """
Archival is run by a tiny team with a goal of staying small. No loss leadership, no enshittification, no investors. When you deploy your site with Archival, you own everything and we make sure it stays online easily and for less than our data-hungry competitors.

Archival itself is open source. The `archival` CLI is free to use and always will be, and you can build archival sites and host them yourself, or deploy them to platforms like Vercel, Netlify, or any static host.

If you're interested in hiring our team to build something custom for you, host a large number of sites on archival, or otherwise find our pricing model imperfect for your use case, reach out to [pricing@archival.dev](mailto:pricing@archival.dev) and we'll get you what you need!
"""
discord_url = "https://discord.gg/Q9Cj6bWTbW"

[header]
sha = ""
display_type = "image"
filename = ""
mime = "image/*"

[[sections]]
title = "Content First"
content = """
Content-first websites: fast, inexpensive, flexible, and future-proof. The Archival editor handles your domain, DNS, deploys, and content for a single monthly price, and gets you online in minutes.
"""

[[sections]]
title = "Built to Last"
content = """
Websites shouldn't rot. Every change to yours is tracked, so you can rebuild it as it was at any point in its history, revert edits from the distant past, and see exactly who made them.
"""

[[sections]]
title = "Totally Yours"
content = """
Start from a beautiful starter site, then customize it in ways big platforms like Squarespace can't. You build with AI and web standards, not platform code or clunky css fields, and editing stays simple.
"""

[[sections]]
title = "Platform Free"
content = """
You own your entire website and data, and we can never change or take it away. No expensive databases, no limiting templates, just a site that becomes uniquely yours over time.
"""

[[videos]]
title = "Launch a Podcast in less than 10 minutes"
poster = "/img/video-poster.jpg"

[videos.video]
display_type = "video"
sha = ""
filename = ""
mime = "video/*"
