order = -1
title = "Archival | Content-First Websites"
description = """
Archival is the simplest way to build an easy-to-maintain website for your business, product, or brand.
"""
header_alt = "archival.dev"
personas_title = "What Can Archival do for Me?"
manifesto_link_title = "Read the archival manifesto"
videos_title = "Show Me How It Works"
contact_title = "Connect With Us"
pricing_title = "Pricing"
pricing_content = """
Archival is run by a tiny team with a goal of staying small. You can use archival for free forever, and you can ship archival sites to platforms like Vercel, Netlify, or host archival websites on your own static servers.

Our goal is to be cheaper and easier than the other options, and our pricing is ridiculously simple - <span class="emphasized">for $14 a month, you get unlimited traffic to your archival-hosted site, the ability to upload large streaming files and add custom domains.

If you’re interested in hiring the archival team to build something custom for you, host a large number of sites on archival, or otherwise find our pricing model imperfect for your use case, reach out to [pricing@archival.dev](mailto:pricing@archival.dev) and we’ll get you what you need!
"""
discord_url = "https://discord.gg/Q9Cj6bWTbW"

[header]
sha = ""
display_type = "image"
filename = ""
mime = "image/*"

[[sections]]
title = "Websites for Everyone"
content = """
Archival's Content-First websites are fast, cheap, flexible, and future-proof. The Archival editor handles everything for your website – domain, DNS, deploys, content management, and more – for a single monthly price. We can get you online in minutes and are the simplest and most reliable way to build a website in existence.
"""

[[sections]]
title = "Maintainable & Durable"
content = """
Archival websites are built to be easy to maintain & last forever. Archival tracks changes to your website, which makes it possible to rebuild your website at any point in its history, revert changes from the distant past, and track who made every change.
"""

[[sections]]
title = "Totally Yours"
content = """
Archival websites can be customized in ways that are impossible on big platforms like Squarespace, and yet it's still far easier to edit the content even after you've made it yours. Archival makes it easy to get started with beautiful starter sites, and then allows you to customize and build using AI and web standards, not custom platform code or clunky css input fields.
"""

[[sections]]
title = "Platform Free"
content = """
Archival, you own your entire website and data, and we can't ever change your website.  Archival takes a new approach to describing content that makes it super easy to update your site but doesn't use expensive databases or limiting templates. Instead of being yet another page on a massive platform, your website becomes uniquely yours over time.
"""

[[videos]]
title = "Launch a Podcast in less than 10 minutes"
poster = "/img/video-poster.jpg"

[videos.video]
display_type = "video"
sha = ""
filename = ""
mime = "video/*"
