title_line_1 = "priced for"
title_line_2 = "everyone"
tagline = "No hidden charges. Just straightforward, simple pricing."

[[tiers]]
icon = "terminal"
name = "Developer"
audience = "Build cool websites, we'll handle the rest"
price = "$5"
term = "/mo"
slug = "developer"
featured = false
cta_label = "Get Started"
cta_url = "https://editor.archival.dev/new"
features = """
- Build anything with Archival
- No centralized platform infrastructure
- Continuous Deployment from a Github repo
- Virtually unlimited traffic
- Large asset uploads (10GB storage included)
- Serverless Carriers included
- Global CDN & Edge Caching
- DNS management & automatic domain mapping
"""

[[tiers]]
icon = "pencil"
name = "Pro"
audience = "Professional features, edit from anywhere"
price = "$15"
term = "/mo"
slug = "pro"
featured = true
cta_label = "Get Started"
cta_url = "https://editor.archival.dev/new"
features = """
- Everything in Developer
- Per-site content editor usable from everywhere
- Custom editors and editor configuration
- Yearly domain renewal (registered with us, limit $40/yr)
- Granular edit history
- AI-assisted automatic site updates
- All our roadmap features, forever
"""

[[tiers]]
icon = "diamond"
name = "White Glove"
audience = "Focus on your business, we'll make sure your website is always up to date"
price = "$150"
term = "/mo"
slug = "white-glove"
featured = false
cta_label = "Talk to us"
cta_url = "mailto:white-glove@archival.dev"
features = """
- Everything in Editor
- Beautiful templates, customized for your business
- Dedicated Site Representative
- 100 included content or visual changes per month
- Special pricing on our network of designers & developers for rich feature & design changes
- Just email us what you want and a real human will handle it
"""
