content = """
__As a Bay Area native and San Francisco resident, I first learned about good food and the joy of sharing it with others as a youngin’ in my parents Sonoma Valley restaurant. Now, those memories drive me to share my passions for all things food and drink.__

__I’m a Sous Chef at Zuni Cafe, the iconic restaurant in San Francisco dedicated to serving the best local ingredients. When i’m not cooking at the restaurant, I’m probably working on my recipe story column called Bounty in the San Francisco Chronicle. Otherwise I’m working on skateboard skills and dreaming of adopting a puppy with my husband.__

### Other stuff he does

- Food Media Lab, 2019

- Panel Member, California Olive Oil Council

- Co-Chair,  Good Food Awards 2015-2019
"""
