order = 3
title = "Archival: easier to update"
body = """
Archival has no database, instead using version control to manage "objects", which are just simple files written in the [TOML](https://toml.io/en/) language.

These objects are organized directly inside a folder, and are loaded at build time so that they're available directly inside your HTML code via Liquid variables.

The objects can contain values of scalar types, which Archival automatically parses. This means that to update an Archival website, all you have to do is add an object file. Archival provides a web interface and mobile apps for updating these files in the same way that you might update a social media post.

This approach also has an intentional side-effect of versioning the content with the website, meaning that you can see any version of the website from all of its history by checking out a given git sha and building it with Archival. Your version control system then also provides the permissioning and history layer that is a large part of many platforms, making Archival stay simple and single-purpose.
"""