content = """
#### Serves 4-6

> *Compelling and dynamic is probably the best way to describe this salad. It has a sweet crunch from thinly sliced fennel and apple, but it’s also sweet and lemony from the vinaigrette. Then, there’s a zingy bite from scallions and shavings of soothing rich, salty cheddar. It’s a salad that feels special, can be piled high into the sky and also tastes great the next day as leftovers.*

¼ cup lemon juice

1 tablespoon white wine vinegar

2 tablespoons honey

½ cup olive oil

Kosher salt

Freshly ground black pepper

¼ cup thinly sliced scallions

3 apples such as Sierra Beauty, Pink Lady or Granny Smith

2 medium fennel bulbs, removed of their stalks and fronds (about 1 pound)

¼ cup roughly chopped dill

½ cup parsley leaves

Aged white cheddar, 2-3 ounces, shaved or sliced very thinly

### Instructions:

In a large bowl add the lemon juice, vinegar, honey and olive oil. Whisk well to incorporate the honey and then season with salt and as much black pepper as you’d like. Whisk well again, add the scallions and set aside.

Cut the apples into ¼-inch slices and add to the bowl with the vinaigrette. Stand one of the fennel bulbs with the root-side down and make a small vertical slice on the narrow edge to create a flat surface. Then put the fennel flat (cut-side) down and cut into ½-inch strips, starting from the top of the bulb. Pop the fibrous center circles out and discard. Place the fennel strips in the bowl with the vinaigrette and repeat with the remaining bulb. Toss the apple and fennel well with the vinaigrette

To serve, add the herbs to the bowl, toss well and pile handful upon handful into a sturdy tall mound. Very thinly shave (with a peeler) or thinly slice the cheddar over the salad.

"""
description = "Compelling and dynamic is probably the best way to describe this salad. It has a sweet crunch from thinly sliced fennel and apple, but it’s also sweet and lemony from the vinaigrette. Then, there’s a zingy bite from scallions and shavings of soothing rich, salty cheddar. It’s a salad that feels special, can be piled high into the sky and also tastes great the next day as leftovers."
image = "https://s.hdnux.com/photos/01/22/60/40/21694470/10/1150x0.jpg"
name = "Crunchy Apple & Fennel Salad With Cheddar"
