name: archival
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  deploy:
    name: "Build & deploy to archival"
    runs-on: ubuntu-latest

    steps:
      - name: Archival Build
        uses: jesseditson/archival@main
  publish-pages:
    runs-on: ubuntu-latest
    environment: archival.dev
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy dist --project-name=archival
