name: archival
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  deploy:
    name: "Build & deploy to archival"
    runs-on: ubuntu-latest

    steps:
      - name: Archival Build
        uses: jesseditson/archival
