name: Archival
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Archival Build
        uses: jesseditson/archival@v0.4.6
        with:
          branch: "gh-pages"
          token: ${{ secrets.GITHUB_TOKEN }}
