name: Archival
on:
  push:
    branches:
      - github.event.repository.default_branch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Archival Build
        uses: jesseditson/archival@v0.4.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
